name       : libsoxr
version    : 0.1.2
release    : 2
source     :
    - http://freefr.dl.sourceforge.net/project/soxr/soxr-0.1.2-Source.tar.xz : 54e6f434f1c491388cd92f0e3c47f1ade082cc24327bdc43762f7d1eefe0c275
license    : LGPL-2.0
summary    : High quality, one-dimensional sample-rate conversion library 
description: |
    High quality, one-dimensional sample-rate conversion library
component  : multimedia.library
patterns:
    - docs: [/usr/share/doc]
emul32     : yes
build      : |
    %cmake . \
        -DWITH_AVFFT=ON \
        -DWITH_DOUBLE_PRECISION=ON \
        -DWITH_LSR_BINDINGS=ON \
        -DWITH_OPENMP=ON \
        -DWITH_PFFFT=ON \
        -DWITH_SIMD=ON \
        -DLIB_INSTALL_DIR=%libdir%
    %make
install    : |
    %make_install
